# This is a sample build configuration for Java (Maven).
# Check our guides at https://confluence.atlassian.com/x/zd-5Mw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: azul/zulu-openjdk-alpine:11

pipelines:
 branches:
  master:
    - step:
        name: Build and Test
        image: maven:3
        caches:
          - maven
        script:
          - echo "Tests started"
          - mvn -B clean verify
          - echo "Tests Completed"
    - step:
        name: Create artifact
        script:
          - tar czfv application.tgz pom.xml src/
        artifacts:
          - application.tgz
    - step:
        name: Deploy to Staging
        deployment: staging
        script:
          - pipe: atlassian/heroku-deploy:0.1.1
            variables:
              HEROKU_API_KEY: $HEROKU_API_KEY
              HEROKU_APP_NAME: $HEROKU_APP_NAME
              ZIP_FILE: "application.tgz"
          - echo "DONE!"